sitename = "ğŸªLe Monde du Flipper ZÃ©roğŸª" 
baseURL = "/"
title = "ğŸªLe Monde du Flipper ZÃ©roğŸª"
author = "ğŸ¦€TounSecğŸ¦€"
enableEmoji = true
hasCJKLanguage = false
pygmentsstyle = "tango"
pygmentscodefences = true
defaultContentLanguage = "fr"
theme = "kaslaanka"

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
  languageName = 'English'
  title = 'ğŸªThe World of Flipper ZeroğŸª'
  
  [[languages.en.menu.primary]]
  name = "Home"
  url = "/en"
  weight = 1

  [[languages.en.menu.primary]]
  name = "About"
  url = "/en/about"
  weight = 2

  [languages.en.params]
  sitename = "ğŸªThe World of Flipper ZeroğŸª"
  copyrights = "ğŸ¦€TounSecğŸ¦€"
  defaultList = "global"
  paginationLen = 3
  projectsURL = "https://github.com/TounSec"
  brief_about = "<center>ğŸ’¡On this blog, you will find several articles and projects concerning the Flipper ZeroğŸ’¡</center>" 

  [languages.fr]
  languageName = 'FranÃ§ais'
  title = "ğŸªLe Monde du Flipper ZÃ©roğŸª"

  [[languages.fr.menu.primary]]
  name = "Accueil"
  url = "/"
  weight = 1

  [[languages.fr.menu.primary]]
  name = "Ã€ propos"
  url = "/about"
  weight = 2

  [languages.fr.params]
  sitename = "ğŸªLe Monde du Flipper ZÃ©roğŸª"
  copyrights = "ğŸ¦€TounSecğŸ¦€"
  defaultList = "global"
  paginationLen = 3
  projectsURL = "https://github.com/TounSec"
  brief_about = "<center>ğŸ’¡Sur ce blog, vous trouverez plusieurs articles et projets, concernant le Flipper ZÃ©roğŸ’¡</center>"

[[params.myprojects]]
name = 'Flipper Zero Official'
description = "Flipper Zero is a portable multi-tool for pentesters and geeks in a toy-like body. It loves hacking digital stuff, such as radio protocols, access control systems, hardware and more. It's fully open-source and customizable, so you can extend it in whatever way you like."
url = 'https://flipperzero.one/'

[[params.myprojects]]
name = 'Awesome Flipper Zero'
description = "ğŸ¬ A collection of awesome resources for the Flipper Zero device."
url = 'https://github.com/djsime1/awesome-flipperzero'

[[params.myprojects]]
name = 'Unleashed'
description = "Unlocked firmware with rolling codes support & community plugins, stable tweaks and games."
url = 'https://github.com/DarkFlippers/unleashed-firmware'

[[params.myprojects]]
name = 'RogueMaster'
description = "Fork of Unleashed firmware with custom graphics, expÃ©rimental tweaks, community plugins and games."
url = 'https://github.com/RogueMaster/flipperzero-firmware-wPlugins'

[[params.myprojects]]
name = 'Xtreme'
description = "Official fork with cleaned up codebase, more module extensions and custom assets."
url = 'https://github.com/ClaraCrazy/Flipper-Xtreme'

[[params.myprojects]]
name = 'SquareWare'
description = "Fork of official firmware which adds custom graphics, community applications and files."
url = 'https://github.com/skizzophrenic/SquachWare-CFW'

[[params.myprojects]]
name = 'OpenHaystack BLE mod'
description = "Very old PoC that makes Flipper Zero behave like an AirTag."
url = 'https://github.com/AlexStrNik/flipperzero-firmware'

[[params.myprojects]]
name = 'My Flipper Shits'
description = "Free and open-source [BadUSB] payloads for Flipper Zero."
url = 'https://github.com/aleff-github/my-flipper-shits/'

[[params.myprojects]]
name = 'UNC0V3R3D BadUSB collection'
description = "Yet another BadUSB collection."
url = 'https://github.com/UNC0V3R3D/Flipper_Zero-BadUsb'

[[params.myprojects]]
name = 'flipperzero-bruteforce'
description = "Generate .sub files to brute force Sub-GHz OOK."
url = 'https://github.com/tobiabocchi/flipperzero-bruteforce'

[[params.myprojects]]
name = 'UberGuidoZ Playground'
description = "Large collection of files, documentation and dumps of all kinds"
url = 'https://github.com/UberGuidoZ/Flipper'

[[params.myprojects]]
name = 'SerialHex2FlipperZeroInfrared'
description = "Convert IR serial message into Flipper Zero compatible IR files."
url = 'https://github.com/maehw/SerialHex2FlipperZeroInfrared'

[[params.myprojects]]
name = 'T119 bruteforcer'
description = "Triggers Retekess T119 restaurant pagers."
url = 'https://github.com/maehw/SerialHex2FlipperZeroInfrared'

[[params.myprojects]]
name = 'FlipperZero-Goodies'
description = "Intercom keys and scripts"
url = 'https://github.com/wetox-team/flipperzero-goodies'
