sitename = "ğŸªLe Monde du Flipper ZÃ©roğŸª" 
baseURL = "/"
title = "ğŸªLe Monde du Flipper ZÃ©roğŸª"
author = "ğŸ¦€TounSecğŸ¦€"
enableEmoji = true
hasCJKLanguage = false
pygmentsstyle = "tango"
pygmentscodefences = true
defaultContentLanguage = "fr"
theme = "kaslaanka"

[markup.goldmark.renderer]
unsafe = true

[languages]
  [languages.en]
  languageName = 'English'
  title = 'ğŸªThe World of Flipper ZeroğŸª'
  
  [[languages.en.menu.primary]]
  name = "Home"
  url = "/en"
  weight = 1

  [[languages.en.menu.primary]]
  name = "About"
  url = "/en/about"
  weight = 2

  [languages.en.params]
  sitename = "ğŸªThe World of Flipper ZeroğŸª"
  copyrights = "ğŸ¦€TounSecğŸ¦€"
  defaultList = "global"
  paginationLen = 3
  projectsURL = "https://github.com/TounSec"
  brief_about = "<center>ğŸ’¡On this blog, you will find several articles and projects concerning the Flipper ZeroğŸ’¡</center>" 

  [languages.fr]
  languageName = 'FranÃ§ais'
  title = "ğŸªLe Monde du Flipper ZÃ©roğŸª"

  [[languages.fr.menu.primary]]
  name = "Accueil"
  url = "/"
  weight = 1

  [[languages.fr.menu.primary]]
  name = "Ã€ propos"
  url = "/about"
  weight = 2

  [languages.fr.params]
  sitename = "ğŸªLe Monde du Flipper ZÃ©roğŸª"
  copyrights = "ğŸ¦€TounSecğŸ¦€"
  defaultList = "global"
  paginationLen = 3
  projectsURL = "https://github.com/TounSec"
  brief_about = "<center>ğŸ’¡Sur ce blog, vous trouverez plusieurs articles et projets, concernant le Flipper ZÃ©roğŸ’¡</center>"

[[params.myprojects]]
name = 'Flipper Zero Official'
description = "Flipper Zero is a portable multi-tool for pentesters and geeks in a toy-like body. It loves hacking digital stuff, such as radio protocols, access control systems, hardware and more. It's fully open-source and customizable, so you can extend it in whatever way you like."
url = 'https://flipperzero.one/'
